### PR TITLE
Add syntax highlighting for PDFs

### PR DESCRIPTION
**Pull request by qrush**
Also gets the test suite happy again, adds bundler.

Going to work on syntax highlighting of site output and better colors soon.

### CODE REVIEW

**Comment by qrush** [comment]
hot damn, that was fast. more coming soon :)

**Comment by schacon** [comment]
i need to eventually pull in these eee-c changes too

**Comment by qrush** [comment]
Also please be aware there's a homebrew-specific path hardcoded in here. I couldn't for the life of me figure out why it won't take the argument as `java -Dhighlight.xslthl.config=file:/...`

https://github.com/schacon/git-scribe/blob/master/docbook-xsl/fo.xsl#L21

**Comment by qrush** [comment]
I was seeing some strange output with his spdy branch. Perhaps you, me, @eee-c and @jayunit should hop on IRC and talk things out? Or just get an email chain going. We're using git-scribe for our backbone on rails book and definitely will be improving this toolchain as we continue writing.

**Comment by qrush** [comment]
Er, @jasonm should join us in IRC :)

**Comment by eee-c** [comment]
Happy to help out however I can. I'm ramping up on another book as well, so I'll be putting more into the tool chain as well. First was going to be syntax highlighting but I don't have to worry about that now - thanks :)

I'm on Ubuntu so that might account for some differences in output.

IIRC the only other major missing feature that I needed for the SPDY book was starting new chapters on the right / recto page for printing.  Pragprog (and I assume other publishers) won't do print media without that.

**Pull request merged**
